input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "HNdWQJ7B*8tSv-U4Ekwc"
    index => "k8s-logs-%{+YYYY.MM.dd}"
    ssl_enabled => true
    ssl_verification_mode => "none"
  }
}
ubuntu@elk:~$
